#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.3.12f1_8afd630d1f5b"
#define UNITY_VERSION_FULL_NICE "2018.3.12f1 (8afd630d1f5b)"
#define UNITY_VERSION_BLD 9108835
#define UNITY_VERSION_DATE 1554475092
#define UNITY_VERSION_WIN "2018.3.12.9108835"
#define UNITY_VERSION_BRANCH "2018.3/release"
